title: AI related topics
description: Here I will be listing some news and topics related to data science and more specific into the field of AI
markdown: GFM
url: "http://akahardzzz0011.github.io/"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
